// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsuFC2y7XIU551Y30-SdYzejR0zQULlFI',
    appId: '1:525197698171:web:ed1d5996a8340229e3aede',
    messagingSenderId: '525197698171',
    projectId: 'fireflutter-cfc80',
    authDomain: 'fireflutter-cfc80.firebaseapp.com',
    storageBucket: 'fireflutter-cfc80.appspot.com',
    measurementId: 'G-MXHGXBPZKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5VCB-tnJhdLWREyjxl1ZbOZLK51Bl_E8',
    appId: '1:525197698171:android:e8376fd752012d6ee3aede',
    messagingSenderId: '525197698171',
    projectId: 'fireflutter-cfc80',
    storageBucket: 'fireflutter-cfc80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFJPpXsLN1f-uRQ5SeidmVlhdKB86T_bE',
    appId: '1:525197698171:ios:59020908acfdd296e3aede',
    messagingSenderId: '525197698171',
    projectId: 'fireflutter-cfc80',
    storageBucket: 'fireflutter-cfc80.appspot.com',
    iosClientId: '525197698171-dja617fv7e17ghmrgchb6kb2op5v5d73.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFJPpXsLN1f-uRQ5SeidmVlhdKB86T_bE',
    appId: '1:525197698171:ios:59020908acfdd296e3aede',
    messagingSenderId: '525197698171',
    projectId: 'fireflutter-cfc80',
    storageBucket: 'fireflutter-cfc80.appspot.com',
    iosClientId: '525197698171-dja617fv7e17ghmrgchb6kb2op5v5d73.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
